### ISSUE TITLE
format does not need to be required

### ISSUE THREAD

**Issue by gmaxey** [cloudbees-io/publish-evidence-item#1]
@karakurty 

I don't think `format` should be required because there is a default value provided in the defintion:

```
  format:
    description: Used to render the evidence item.
    default: MARKDOWN
    required: true
```
